FROM node:18-alpine
RUN apk add --no-cache python3 py3-pip ffmpeg deno && \
    pip3 install --break-system-packages yt-dlp
WORKDIR /app
COPY package*.json ./
RUN npm install
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host"]
